### ISSUE TITLE
Tauri App can only run once due to a output filename collision

### ISSUE THREAD

**Issue by Evolinox** [Evolinox/Communities#1]
When building the App, there will be an output filename collision with the app_lib, causing an Issue and preventing the App to run again after the first Time.

```bash
warning: output filename collision.
The lib target `app_lib` in package `communities v0.0.0 (/Users/pascal/Repositories/Communities/src-tauri)` has the same output filename as the lib target `app_lib` in package `communities v0.0.0 (/Users/pascal/Repositories/Communities/src-tauri)`.
Colliding filename is: /Users/pascal/Repositories/Communities/src-tauri/target/debug/deps/libapp_lib.rlib
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
thread 'main' panicked at src/cargo/core/compiler/fingerprint/mod.rs:1103:13:
assertion failed: mtimes.insert(output.clone(), mtime).is_none()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ELIFECYCLE  Command failed with exit code 101.
```

Current fix is to delete the `target`-Folder and build the App again

**Comment by Evolinox** [comment]
Renaming `app_lib` to `communities_lib` also doesn't help with this Issue.

```bash
warning: output filename collision.
The lib target `communities_lib` in package `communities v0.0.0 (/Users/pascal/Repositories/Communities/src-tauri)` has the same output filename as the lib target `communities_lib` in package `communities v0.0.0 (/Users/pascal/Repositories/Communities/src-tauri)`.
Colliding filename is: /Users/pascal/Repositories/Communities/src-tauri/target/debug/deps/libcommunities_lib.rlib
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
thread 'main' panicked at src/cargo/core/compiler/fingerprint/mod.rs:1103:13:
assertion failed: mtimes.insert(output.clone(), mtime).is_none()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ELIFECYCLE  Command failed with exit code 101.
```

The Issue still persist after the first run.

**Comment by Evolinox** [comment]
Fixed this Issue by removing `lib` from `lib.crate-type`
```toml
[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
```
